### ISSUE TITLE
Movie Maker : no file is created

### ISSUE THREAD

**Issue by imrahjel** [akiver/CSGO-Demos-Manager#344] opened 2018-10-15 05:47 UTC
Hello,
I tried many options (both encoders, windowed or fullscreened, well i think I tried everything) always ending the same way :

- demo is launched, and play/stop as expected
- no raw file is created
- no movie file is created
- only the WAV file is created.

I really don't know if this is a bug or a misuse, please tell me where I'm wrong if this is on my side.
Config : W10, GeForce1060, CSGO last update running full quality.
Thanks,
Imrahjel.

**Comment by pewpewpew47** [comment] 2018-10-17 14:36
Same thing happened to me as well. I can open all the little apps that is downloaded (Virtual Dub...) but nothing is coming out when the generate button is pressed except a small size wav file. What is going on???

**Comment by pewpewpew47** [comment] 2018-10-21 08:01
Akiver thank u for adding the labels and I have been testing daily to see if the problem is fixed but still no. And btw, the movie maker opens csgo and the capture process seems to be fast-forwarded, and no matter what tick I choose to capture, it will always be the same scenes in csgo by defult.

**Comment by imrahjel** [comment] 2018-10-21 09:36
yes, thansk for the update.
I tried many folders, thinking about credentials issues, but nothing more or less happened.

**Comment by HORSEKC** [comment] 2018-11-09 09:03
Try this:
* Raw files destination folder must be the default location, as in: \Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo

Worked for me on this exact same issue.

**Comment by pewpewpew47** [comment] 2018-11-10 01:34
HORSEKC,
You are a real legend my mate.
It worked perfectly now.
A few question to ask u tho:
1. Are RAW files images and sounds captured?
2. Usually if I want to do a 1080p 60fps clip, even less than a minute, it requires 10G+ disk space, however, if I only use default RAW files folder, it would eat up all my C drive, which is essentially my SSD. Is there a way to solve this other than spend more money on a better SSD?
Thank you so much bro u r amazing.
Ali

**Comment by pewpewpew47** [comment] 2018-11-10 01:50
Update:
Hey u know what, if I set output resolution to 1280*720 then the movie outcome becomes so smooth. Can it just be the limitation of my computer hardware? I though I5 8400 and 16G RAM will get the job done...

**Comment by imrahjel** [comment] 2018-11-10 08:19
@HORSEKC thanks for the inout, i'll try soon.
@pewpewpew47 you might want to test with symbolic link, aka LN under linux, and for Win10 -> https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc753194(v=ws.10)

**Comment by HORSEKC** [comment] 2018-11-11 04:05
@pewpewpew47 
1. Yes. Output folder is the rendered video destination.
2. It might be worth looking into installing a second steam and CSGO for moviemaking on another drive?
To add, 1280x720 is 1/4th of 1080p bitrate and uncompressed 60fps 1080p material is a lot of data so maybe the bottleneck could be your SSD writing speed more likely than processor or RAM.

**Comment by pewpewpew47** [comment] 2018-11-15 10:53
@HORSEKC  Cheers buddy I am now using recording tools to just capture high lights and low lights. But I am still using Demo manager to play the demos. It feels way smoother than just checking out demos in game.

**Comment by akiver** [comment] 2018-12-09 16:15
It should be fixed in 2.13.5

**Closed by akiver** 2018-12-09 16:15 UTC
Labels: bug, duplicate
