### ISSUE TITLE
Can't view lowlights from enemy POV

### ISSUE THREAD

**Issue by Kazken** [akiver/CSGO-Demos-Manager#445] opened 2020-04-24 17:40 UTC
I noticed that when trying to view a demo, it's possible to view your lowlights from Player A's point of view, but not possible to view lowlights from the enemy that killed Player A. I am trying to figure out how I am dying in a game, but it's hard to do without this functionality. 

Let me know if you need additional information.

**Comment by akiver** [comment] 2020-05-12 03:23
When you click on "Watch lowlights" you will have the choice between "Player POV" or "Enemy POV".
Click on "Enemy POV" and you will see your lowlights from enemy's perspective.

You can do it quickly from the scoreboard too
![https://www.csgo-demos-manager.com/docs/watch/scoreboard-highlow.png](https://www.csgo-demos-manager.com/docs/watch/scoreboard-highlow.png)

**Comment by Kazken** [comment] 2020-05-15 20:39
Yeah, clicking on that "Watch Lowlights" brings up that menu, but when I launch the demo from Enemy POV it will just start the demo from the beginning and not like it would when selecting player POV

**Comment by wilsontgh** [comment] 2020-05-18 18:02
@Kazken I had the same problem. After I connected my Steam account in Settings it worked fine 😃

**Comment by akiver** [comment] 2020-05-26 02:46
@Kazken I can't reproduce the issue.
Could you please upload a demo affected and the steps to reproduce it?

**Comment by akiver** [comment] 2021-02-04 04:07
It should be fixed with v2.13.15

**Closed by akiver** 2021-02-04 04:07 UTC
Labels: question, reply-needed
