### ISSUE TITLE
Error while try to get suspects information

### ISSUE THREAD

**Issue by zingz0r** [akiver/CSGO-Demos-Manager#65] opened 2016-03-10 17:59 UTC
Reproduce:
Right click on demo -> Add players to suspects list -> Error while try to get suspects information

**Comment by akiver** [comment] 2016-03-10 21:04
Could you send me the errors.log file plz?
This issue seems to be related to the Steam API or your connection.

**Comment by zingz0r** [comment] 2016-03-12 00:37
Sure, but could you tell me please where is it located, because if I go to [Settings] -> [Errors log file] it only  opens the 'My Computer'.

**Comment by akiver** [comment] 2016-03-12 13:52
@zingz0r It's located in the app installation folder.

**Comment by zingz0r** [comment] 2016-03-13 08:28
Sorry but there's no error.log on my pc.
What i tried:
 - checked csgo demos dir. (no error.log)
 - reinstalled app and checked dir. (no error.log)
 - created an error.log, restarted app and reproduced the steps (#65) (error.log empty)

**Comment by akiver** [comment] 2016-03-19 17:36
Should be fixed with the version 2.5.0.

**Closed by akiver** 2016-03-19 17:36 UTC
Labels: bug

**Comment by Cylo0n** [comment] 2016-03-26 15:51
Sorry. Still getting this error while adding to suspect list.

**Comment by zingz0r** [comment] 2016-04-10 15:36
im still getting it too

**Comment by Cylo0n** [comment] 2016-07-08 12:18
I justed checked it with new Version but the problem isn't solved yet. Starting Application i am getting the error.

**Comment by akiver** [comment] 2016-07-09 11:29
Still no errors.log? You can navigate to it from settings.

**Comment by Cylo0n** [comment] 2016-07-13 14:54
No there's no error log in application folder. Or in other words i can't find any log file.
